import { CodeLanguage } from '../types';

export interface GitHubActionsConfig {
  testSuiteName: string;
  targetUrl: string;
  codeLanguage: CodeLanguage;
  nodeVersion?: string;
  playwrightVersion?: string;
  testFileName?: string;
  runOn?: ('push' | 'pull_request')[];
  branches?: string[];
  schedule?: string; // cron expression
  browsers?: ('chromium' | 'firefox' | 'webkit')[];
  workers?: number;
  retries?: number;
}

/**
 * Generate a GitHub Actions workflow YAML for running Playwright tests
 */
export function generateGitHubActionsWorkflow(config: GitHubActionsConfig): string {
  const {
    testSuiteName,
    targetUrl,
    codeLanguage,
    nodeVersion = '20',
    playwrightVersion = '1.56',
    testFileName = 'test.spec',
    runOn = ['push', 'pull_request'],
    branches = ['main', 'master', 'develop'],
    schedule,
    browsers = ['chromium'],
    workers = 1,
    retries = 2,
  } = config;

  const extension = codeLanguage === 'typescript' ? 'ts' : 'js';
  const fullTestFileName = `${testFileName}.${extension}`;

  // Build trigger section
  const triggers = [];
  if (runOn.includes('push')) {
    triggers.push(`  push:
    branches: [${branches.map(b => `'${b}'`).join(', ')}]`);
  }
  if (runOn.includes('pull_request')) {
    triggers.push(`  pull_request:
    branches: [${branches.map(b => `'${b}'`).join(', ')}]`);
  }
  if (schedule) {
    triggers.push(`  schedule:
    - cron: '${schedule}'`);
  }

  // Add workflow_dispatch for manual triggering
  triggers.push(`  workflow_dispatch:`);

  const triggerSection = triggers.join('\n');

  // Build browser matrix
  const browserMatrix = browsers.length > 1
    ? `browser: [${browsers.map(b => `'${b}'`).join(', ')}]`
    : '';

  const matrixSection = browserMatrix
    ? `    strategy:
      matrix:
        ${browserMatrix}`
    : '';

  const browserSuffix = browsers.length > 1 ? '-${{ matrix.browser }}' : '';

  return `# Auto-generated GitHub Actions workflow for ${testSuiteName}
# Generated by Pathfinder - Intelligent Automated Testing Platform
# ${new Date().toISOString()}

name: ${testSuiteName} - Playwright Tests

on:
${triggerSection}

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
${matrixSection}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright@${playwrightVersion} install --with-deps${browsers.length === 1 ? ` ${browsers[0]}` : ''}

      - name: Run Playwright tests
        run: npx playwright test ${fullTestFileName}${browsers.length > 1 ? ' --project=${{ matrix.browser }}' : ''}
        env:
          TEST_TARGET_URL: ${targetUrl}
          PLAYWRIGHT_WORKERS: ${workers}
          PLAYWRIGHT_RETRIES: ${retries}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results${browserSuffix}
          path: |
            playwright-report/
            test-results/
          retention-days: 30

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots${browserSuffix}
          path: test-results/**/*.png
          retention-days: 7

      - name: Publish test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report${browserSuffix}
          path: playwright-report/
          retention-days: 30
`;
}

/**
 * Generate a Playwright configuration file for the project
 */
export function generatePlaywrightConfig(config: GitHubActionsConfig): string {
  const { codeLanguage, browsers = ['chromium'], workers = 1, retries = 2 } = config;

  const importStatement = codeLanguage === 'typescript'
    ? `import { defineConfig, devices } from '@playwright/test';`
    : `const { defineConfig, devices } = require('@playwright/test');`;

  const exportStatement = codeLanguage === 'typescript' ? 'export default' : 'module.exports =';

  // Build projects configuration
  const projectsConfig = browsers.map(browser => {
    const deviceMap: Record<string, string> = {
      chromium: 'Desktop Chrome',
      firefox: 'Desktop Firefox',
      webkit: 'Desktop Safari',
    };

    return `    {
      name: '${browser}',
      use: { ...devices['${deviceMap[browser]}'] },
    }`;
  }).join(',\n');

  return `// Auto-generated Playwright configuration
// Generated by Pathfinder - Intelligent Automated Testing Platform

${importStatement}

${exportStatement} defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? ${retries} : 0,
  workers: process.env.CI ? ${workers} : undefined,
  reporter: [
    ['html'],
    ['json', { outputFile: 'test-results/results.json' }],
    ['junit', { outputFile: 'test-results/junit.xml' }],
  ],
  use: {
    baseURL: process.env.TEST_TARGET_URL || 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
${projectsConfig}
  ],
});
`;
}

/**
 * Generate package.json scripts for running tests
 */
export function generatePackageJsonScripts(): Record<string, string> {
  return {
    'test': 'playwright test',
    'test:headed': 'playwright test --headed',
    'test:debug': 'playwright test --debug',
    'test:ui': 'playwright test --ui',
    'test:report': 'playwright show-report',
  };
}

/**
 * Generate a README for the CI setup
 */
export function generateCIReadme(config: GitHubActionsConfig): string {
  const { testSuiteName, targetUrl, codeLanguage } = config;

  return `# ${testSuiteName} - CI/CD Setup

This directory contains the auto-generated GitHub Actions workflow for running Playwright tests.

## Generated by Pathfinder
**Intelligent Automated Testing Platform**
Generated on: ${new Date().toLocaleString()}

## Overview

- **Test Suite**: ${testSuiteName}
- **Target URL**: ${targetUrl}
- **Language**: ${codeLanguage === 'typescript' ? 'TypeScript' : 'JavaScript'}

## Setup Instructions

### 1. Install Dependencies

\`\`\`bash
npm install --save-dev @playwright/test@1.56
npx playwright install
\`\`\`

### 2. Add Test File

Copy your generated Playwright test code to \`tests/test.spec.${codeLanguage === 'typescript' ? 'ts' : 'js'}\`

### 3. Commit Workflow

The GitHub Actions workflow has been created at \`.github/workflows/${testSuiteName.toLowerCase().replace(/\s+/g, '-')}.yml\`

Commit and push to your repository:

\`\`\`bash
git add .github/workflows/
git add tests/
git add playwright.config.${codeLanguage === 'typescript' ? 'ts' : 'js'}
git commit -m "Add Playwright CI workflow for ${testSuiteName}"
git push
\`\`\`

### 4. Monitor Test Runs

Visit your repository's **Actions** tab to monitor test executions.

## Running Tests Locally

\`\`\`bash
# Run all tests
npm test

# Run tests in headed mode (see browser)
npm run test:headed

# Run tests in debug mode
npm run test:debug

# Open Playwright UI
npm run test:ui

# View test report
npm run test:report
\`\`\`

## CI/CD Triggers

This workflow runs on:
- Push to main/master/develop branches
- Pull requests to main/master/develop branches
- Manual trigger via GitHub Actions UI
${config.schedule ? `- Scheduled: ${config.schedule}` : ''}

## Test Results

Test results, screenshots, and HTML reports are automatically uploaded as artifacts after each run.

## Configuration

Edit \`.github/workflows/${testSuiteName.toLowerCase().replace(/\s+/g, '-')}.yml\` to customize:
- Trigger events
- Node.js version
- Playwright version
- Browser matrix
- Retry and worker settings

## Support

For issues or questions, refer to:
- [Playwright Documentation](https://playwright.dev)
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
`;
}
