import { CodeLanguage } from '../types';

export interface GitLabCIConfig {
  testSuiteName: string;
  targetUrl: string;
  codeLanguage: CodeLanguage;
  nodeVersion?: string;
  playwrightVersion?: string;
  testFileName?: string;
  browsers?: ('chromium' | 'firefox' | 'webkit')[];
  workers?: number;
  retries?: number;
  runOnSchedule?: boolean;
  scheduleInterval?: string;
}

/**
 * Generate a GitLab CI/CD pipeline YAML for running Playwright tests
 */
export function generateGitLabCIPipeline(config: GitLabCIConfig): string {
  const {
    testSuiteName,
    targetUrl,
    codeLanguage,
    nodeVersion = '20',
    playwrightVersion = '1.56',
    testFileName = 'test.spec',
    browsers = ['chromium'],
    workers = 1,
    retries = 2,
  } = config;

  const extension = codeLanguage === 'typescript' ? 'ts' : 'js';
  const fullTestFileName = `${testFileName}.${extension}`;

  // Build browser jobs
  const browserJobs = browsers.map(browser => {
    const jobName = `test:${browser}`;
    const browserInstall = browser === 'chromium' ? 'chromium' : browser;

    return `${jobName}:
  stage: test
  image: mcr.microsoft.com/playwright:v${playwrightVersion}-focal
  script:
    - npm ci
    - npx playwright install --with-deps ${browserInstall}
    - npx playwright test ${fullTestFileName} --project=${browser}
  variables:
    TEST_TARGET_URL: ${targetUrl}
    PLAYWRIGHT_WORKERS: ${workers}
    PLAYWRIGHT_RETRIES: ${retries}
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 30 days
  retry:
    max: ${retries}
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  only:
    - main
    - master
    - develop
    - merge_requests`;
  }).join('\n\n');

  return `# Auto-generated GitLab CI/CD pipeline for ${testSuiteName}
# Generated by Pathfinder - Intelligent Automated Testing Platform
# ${new Date().toISOString()}

image: node:${nodeVersion}

stages:
  - install
  - test
  - report

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"

install_dependencies:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 day
  only:
    - main
    - master
    - develop
    - merge_requests

${browserJobs}

pages:
  stage: report
  dependencies:
${browsers.map(b => `    - test:${b}`).join('\n')}
  script:
    - mkdir -p public
    - cp -r playwright-report/* public/ || echo "No report to publish"
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main
    - master
`;
}

/**
 * Generate a GitLab CI variables configuration guide
 */
export function generateGitLabCIVariables(config: GitLabCIConfig): string {
  const { testSuiteName, targetUrl } = config;

  return `# GitLab CI/CD Variables for ${testSuiteName}

## Required Variables

These variables should be set in your GitLab project settings:
**Settings > CI/CD > Variables**

| Variable Name | Description | Value | Protected | Masked |
|---------------|-------------|-------|-----------|--------|
| \`TEST_TARGET_URL\` | Target URL for tests | \`${targetUrl}\` | ✓ | ✗ |
| \`PLAYWRIGHT_WORKERS\` | Number of parallel workers | \`1\` | ✗ | ✗ |
| \`PLAYWRIGHT_RETRIES\` | Number of retry attempts | \`2\` | ✗ | ✗ |

## Optional Variables

| Variable Name | Description | Default | Protected | Masked |
|---------------|-------------|---------|-----------|--------|
| \`PLAYWRIGHT_BROWSER_TIMEOUT\` | Browser timeout (ms) | \`30000\` | ✗ | ✗ |
| \`PLAYWRIGHT_TEST_TIMEOUT\` | Test timeout (ms) | \`30000\` | ✗ | ✗ |
| \`PLAYWRIGHT_HEADED\` | Run in headed mode | \`false\` | ✗ | ✗ |

## Setting Variables via GitLab UI

1. Navigate to **Settings > CI/CD**
2. Expand **Variables** section
3. Click **Add variable**
4. Enter variable name and value
5. Configure protection and masking options
6. Click **Add variable**

## Setting Variables via CLI

\`\`\`bash
# Set a variable using GitLab CLI
glab variable set TEST_TARGET_URL --value="${targetUrl}"
glab variable set PLAYWRIGHT_WORKERS --value="1"
glab variable set PLAYWRIGHT_RETRIES --value="2"
\`\`\`

## Using Variables in Pipeline

Variables are automatically available in the pipeline environment and can be referenced in \`.gitlab-ci.yml\`:

\`\`\`yaml
script:
  - echo "Testing \${TEST_TARGET_URL}"
  - npx playwright test --workers=\${PLAYWRIGHT_WORKERS}
\`\`\`
`;
}

/**
 * Generate a README for GitLab CI setup
 */
export function generateGitLabCIReadme(config: GitLabCIConfig): string {
  const { testSuiteName, targetUrl, codeLanguage, browsers = ['chromium'] } = config;

  return `# ${testSuiteName} - GitLab CI/CD Setup

This directory contains the auto-generated GitLab CI/CD pipeline for running Playwright tests.

## Generated by Pathfinder
**Intelligent Automated Testing Platform**
Generated on: ${new Date().toLocaleString()}

## Overview

- **Test Suite**: ${testSuiteName}
- **Target URL**: ${targetUrl}
- **Language**: ${codeLanguage === 'typescript' ? 'TypeScript' : 'JavaScript'}
- **Browsers**: ${browsers.join(', ')}

## Setup Instructions

### 1. Install Dependencies Locally

\`\`\`bash
npm install --save-dev @playwright/test@1.56
npx playwright install
\`\`\`

### 2. Add Test File

Copy your generated Playwright test code to \`tests/test.spec.${codeLanguage === 'typescript' ? 'ts' : 'js'}\`

### 3. Add Pipeline Configuration

The GitLab CI pipeline has been created at \`.gitlab-ci.yml\` in your project root.

### 4. Configure CI Variables

Set the following variables in **Settings > CI/CD > Variables**:

- \`TEST_TARGET_URL\`: ${targetUrl}
- \`PLAYWRIGHT_WORKERS\`: 1
- \`PLAYWRIGHT_RETRIES\`: 2

See \`GITLAB_CI_VARIABLES.md\` for detailed variable configuration.

### 5. Commit and Push

\`\`\`bash
git add .gitlab-ci.yml
git add tests/
git add playwright.config.${codeLanguage === 'typescript' ? 'ts' : 'js'}
git commit -m "Add Playwright CI pipeline for ${testSuiteName}"
git push origin main
\`\`\`

### 6. Monitor Pipeline

Visit your project's **CI/CD > Pipelines** page to monitor test executions.

## Pipeline Stages

1. **install** - Install Node.js dependencies
2. **test** - Run Playwright tests across configured browsers
3. **report** - Publish test reports to GitLab Pages

## Running Tests Locally

\`\`\`bash
# Run all tests
npm test

# Run tests in headed mode
npm run test:headed

# Run tests in debug mode
npm run test:debug

# Open Playwright UI
npm run test:ui

# View test report
npm run test:report
\`\`\`

## Pipeline Triggers

This pipeline runs on:
- Push to main/master/develop branches
- Merge requests to main/master/develop branches
- Manual trigger via GitLab CI/CD UI

## Test Results

- Test results are available as pipeline artifacts
- HTML reports are published to GitLab Pages (if configured)
- Screenshots and videos are uploaded for failed tests

## Browser Matrix

Tests run in parallel across the following browsers:
${browsers.map(b => `- ${b.charAt(0).toUpperCase() + b.slice(1)}`).join('\n')}

## Viewing Test Reports

### Via GitLab Pages

After successful pipeline execution, view the HTML report at:
\`https://<your-username>.gitlab.io/<project-name>/\`

### Via Artifacts

1. Navigate to **CI/CD > Pipelines**
2. Click on the pipeline run
3. Click on a job (e.g., \`test:chromium\`)
4. Download artifacts from the right sidebar
5. Extract and open \`playwright-report/index.html\`

## Customization

Edit \`.gitlab-ci.yml\` to customize:
- Node.js Docker image version
- Playwright version
- Browser matrix
- Retry and worker settings
- Cache configuration
- Artifact retention

## Support

For issues or questions, refer to:
- [Playwright Documentation](https://playwright.dev)
- [GitLab CI/CD Documentation](https://docs.gitlab.com/ee/ci/)
- [Playwright GitLab CI Guide](https://playwright.dev/docs/ci#gitlab-ci)
`;
}

/**
 * Generate GitLab Pages configuration for test reports
 */
export function generateGitLabPagesConfig(): string {
  return `# GitLab Pages Configuration

## Enabling GitLab Pages for Test Reports

GitLab Pages allows you to publish your Playwright HTML test reports as a static website.

### Setup Steps

1. **Ensure Pipeline Includes Pages Job**

   The generated \`.gitlab-ci.yml\` already includes a \`pages\` job that publishes reports.

2. **Configure GitLab Pages Settings**

   - Navigate to **Settings > Pages**
   - Select visibility level (Private/Internal/Public)
   - Click **Save changes**

3. **Access Your Reports**

   After the pipeline runs successfully, your reports will be available at:
   \`https://<namespace>.gitlab.io/<project-name>/\`

### Pages Job Behavior

- The \`pages\` job runs in the \`report\` stage
- It copies contents of \`playwright-report/\` to \`public/\`
- Reports are only published from the default branch (main/master)
- Reports are retained for 30 days

### Custom Domain

To use a custom domain for your test reports:

1. Navigate to **Settings > Pages**
2. Click **New Domain**
3. Enter your custom domain
4. Follow DNS configuration instructions
5. Upload SSL certificate (optional)

### Report Index

The main report is accessible at:
\`https://<namespace>.gitlab.io/<project-name>/index.html\`

### Security Considerations

- Set Pages visibility to **Private** for internal test reports
- Use **Internal** for company-wide access
- Only use **Public** if reports don't contain sensitive information
`;
}
